### ISSUE TITLE
「CRITICAL」:Arbitrary file reading caused by directory traversal from download func

### ISSUE THREAD

**Issue by Bin4xin** [myeeboy/XDocService#1]
hi ! myeeboy ,i'm bin4xin:

我是一名白帽子，最近我發現您的XDocService展示網路存在任意文件讀取，危害很大，請重視！無意冒犯；
以下是我的滲透過程：

- 註冊完成
- 上傳一個任意文件，點擊url連接：
  - ```java
     http://www.xdocin.com/xdoc?_key={key}&_func=down&_dir={../../../path/to/files/you/want} 
      ```
**觸發漏洞url如上**
下面是部分截圖訊息：

![image](https://user-images.githubusercontent.com/57884471/104533969-577a4200-564e-11eb-96e5-502b880f9926.png)


如果您有問題請聯繫電郵：`chihou.pro@gmail.com`。

**Comment by myeeboy** [comment]
已经修复，多谢
